### ISSUE TITLE
utils/genprimopcode/ParserM.hs fails to compile on GHC 7.10

### ISSUE THREAD

**Issue by cstrahan** [ghcjs/ghcjs-boot#10]
`utils/genprimopcode/ParserM.hs` fails to compile on GHC 7.10:

    /nix/store/132fqqki4ak5dxi79zzyx63b4vnqwwsm-ghc-7.10.0.20150123/bin/ghc -o genprimopcode -O Main.hs +RTS -K128M
    [1 of 5] Compiling ParserM          ( ParserM.hs, ParserM.o )
    
    ParserM.hs:26:10:
        No instance for (Applicative ParserM)
          arising from the superclasses of an instance declaration
        In the instance declaration for ‘Monad ParserM’
    ghcjs-boot: error running: /nix/store/132fqqki4ak5dxi79zzyx63b4vnqwwsm-ghc-7.10.0.20150123/bin/ghc -o genprimopcode -O Main.hs +RTS -K128M
    exit status: 1
    stderr:
    ParserM.hs:26:10:
        No instance for (Applicative ParserM)
          arising from the superclasses of an instance declaration
        In the instance declaration for ‘Monad ParserM’

**Comment by cstrahan** [comment]
This patch seems to be sufficient:

``` patch
diff --git a/utils/genprimopcode/ParserM.hs b/utils/genprimopcode/ParserM.hs
index aaaf6ac..b83b695 100644
--- a/utils/genprimopcode/ParserM.hs
+++ b/utils/genprimopcode/ParserM.hs
@@ -17,12 +17,20 @@ module ParserM (
     happyError
  ) where
 
+import Control.Monad (ap, liftM)
 import Data.Word (Word8)
 import Data.Char (ord)
 
 -- Parser Monad
 newtype ParserM a = ParserM (AlexInput -> St -> Either String (AlexInput, St, a))
 
+instance Functor ParserM where
+    fmap = liftM
+
+instance Applicative ParserM where
+    pure  = return
+    (<*>) = ap
+
 instance Monad ParserM where
     ParserM m >>= k = ParserM $ \i s -> case m i s of
                                             Right (i', s', x) ->
```

**Comment by cstrahan** [comment]
Whoops, looks like https://github.com/ghcjs/ghcjs-boot/pull/9 beat me to it.

**Comment by ddssff** [comment]
Yeah, and the 7.10 branch beat *me* to it!

**Comment by cstrahan** [comment]
This was resolved; closing.
