### ISSUE TITLE
ParserM needs an Applicative instance

### ISSUE THREAD

**Issue by tel** [ghcjs/ghcjs-boot#13]
... in order to compile under GHC 7.10.

https://github.com/ghcjs/ghcjs-boot/blob/master/utils/genprimopcode/ParserM.hs

**Comment by luite** [comment]
Has been fixed already in the ghc-7.10 branch

**Comment by tel** [comment]
Oh! Guess I need to boot from that branch somehow.

**Comment by luite** [comment]
See ghcjs readme

**Comment by tel** [comment]
`--ghcjs-boot-dev-branch ghc-7.10`, I suppose.

**Comment by tel** [comment]
Perfect, yup, thanks and sorry about the noise!
