### ISSUE TITLE
cloning fails in  aeson submodule

### ISSUE THREAD

**Issue by hvr** [ghcjs/ghcjs-boot#19]
```
$ git clone --recursive https://github.com/ghcjs/ghcjs-boot.git
...
Checking connectivity... done.
Submodule path 'ghcjs/ghcjs-base': checked out 'ed1f69ee3d485d6659bb6fc4a395f66c9d8a0a7e'
Cloning into 'ghcjs/ghcjs-prim'...
remote: Counting objects: 129, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 129 (delta 0), reused 0 (delta 0), pack-reused 124
Receiving objects: 100% (129/129), 23.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (47/47), done.
Checking connectivity... done.
Submodule path 'ghcjs/ghcjs-prim': checked out '8e003e1a1df10233bc3f03d7bbd7d37de13d2a84'
Unable to checkout '67ea6491600cae9a6bf8a87a558badadffcac791' in submodule path 'boot/aeson'
```

...basically, the commit doesn't exist anymore in the upstream repo

**Comment by luite** [comment]
gr, why does everyone suddenly start removing commits from their repos...

**Comment by hvr** [comment]
@luite because they can =)

...for that reason we have a somewhat elaborate git mirroring in place at http://git.haskell.org together with some hooks to ensure less fragile submodule gitlinks... :-)

**Comment by marcelbuesing** [comment]
[67ea6491600cae9a6bf8a87a558badadffcac791](https://github.com/bos/aeson/commit/67ea6491600cae9a6bf8a87a558badadffcac791)
For whatever reason now seems to be: 
[cbf365b1bde7007d6c4613ba2cebf6f3b17e7309](https://github.com/bos/aeson/commit/cbf365b1bde7007d6c4613ba2cebf6f3b17e7309)

**Comment by hvr** [comment]
fwiw, this seems to have been resolved now...
