### ISSUE TITLE
Fail to ghcjs-boot for ghc-7.10 due to cabal-solver failure

### ISSUE THREAD

**Issue by hvr** [ghcjs/ghcjs-boot#20]
This seems to have been caused by 19620b69257115a69306eec505a97ac843055e92

```
$ ghcjs-boot --clean --dev --no-prof --no-haddock --ghcjs-boot-dev-branch ghc-7.10
...
Choosing modular solver.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: aeson-0.8.1.0 (user goal)
next goal: attoparsec (user goal)
rejecting: attoparsec-0.12.1.3 (conflict: aeson => attoparsec>=0.13.0.0)
Dependency tree exhaustively searched.
ghcjs-boot: error running: /home/hvr/.cabal/bin/cabal --config-file /home/hvr/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs/cabalBootConfig install ./boot/async ./boot/aeson ./boot/attoparsec ./boot/case-insensitive ./boot/dlist ./boot/extensible-exceptions ./boot/hashable ./boot/mtl ./boot/old-time ./boot/parallel ./boot/scientific ./boot/stm ./boot/syb ./boot/text ./boot/unordered-containers ./boot/vector ./ghcjs/ghcjs-base --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /home/hvr/.cabal/bin/ghcjs --with-hc-pkg /home/hvr/.cabal/bin/ghcjs-pkg --prefix /home/hvr/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs --disable-documentation --haddock-html --haddock-hyperlink-source --disable-library-profiling --root-cmd /home/hvr/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs/run.sh -v2 --dry-run
exit status: 1
stderr: Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
cabal: Could not resolve dependencies:
trying: aeson-0.8.1.0 (user goal)
next goal: attoparsec (user goal)
rejecting: attoparsec-0.12.1.3 (conflict: aeson => attoparsec>=0.13.0.0)
Dependency tree exhaustively searched.
```

**Comment by hvr** [comment]
Fwiw, the commit corresponding to the  old https://github.com/bos/aeson/commits/76cc2f8b7cd708b9f68b99e2ed2588777dcd9d19 would have rather been https://github.com/bos/aeson/commits/0c907c7d3ddbff6f3ea0fbaaa9b0c6547b83dcff

and from the looks of it, @bos seems to have completely rewritten most/all of aeson's Git history, maybe he's using some sort of mirroring from some non-Git repo which subtly changed how it maps to Git commits, thereby causing the Git commit ids to new ones (thereby also losing all GitHub-annotated code-comments, e.g. https://github.com/bos/aeson/commit/730a8c42b75f38e241da39933b03735a7c905538 won't be easily discoverable anymore)

**Comment by bos** [comment]
Yes, there was a little hg-git accident at the weekend :-(

**Comment by luite** [comment]
Oh I hope I didn't pull in experimental changes with my commit. I'm a bit short on time this week with a talk in Brisbane coming up and then some long flights to Zurihac. After that I hope to merge `improved-base` and clean up the ghcjs-boot mess a bit.

**Comment by cstrahan** [comment]
@luite 

> After that I hope to merge improved-base and clean up the ghcjs-boot mess a bit.

In the interim, do you think you could fix the Aeson ref, please? We're still seeing build failures in Nixpkgs:

* Build log: http://hydra.nixos.org/build/22201079/nixlog/47
* https://github.com/NixOS/nixpkgs/issues/7881
* https://github.com/ghcjs/ghcjs/issues/345

**Comment by cstrahan** [comment]
I opened a PR to switch the aeson ref: https://github.com/ghcjs/ghcjs-boot/pull/22

**Comment by luite** [comment]
wait, did I solve this already?

**Comment by hamishmack** [comment]
I presume if this is not fixed already in `master` it should be working in `ghc-8.0`
