### ISSUE TITLE
wrong primitive submodule

### ISSUE THREAD

**Issue by tonyday567** [ghcjs/ghcjs-boot#21]
I think that bos/mwc-random#48 is due to an incorrect primitive submodule hook.

**Comment by luite** [comment]
is this on the 7.10 branch?

**Comment by tonyday567** [comment]
Yes.  installed with `ghcjs-boot --dev --ghcjs-boot-dev-branch ghc-7.10`

**Comment by tonyday567** [comment]
Guessing that haskell/primitive@29cb0db59803c9d9181f7c4ce35ef1c6cbc6ccfb was the released one for 0.5.4.0, and subsequent commits were experimental.

**Comment by luite** [comment]
sounds plausible. I've set the `master` and `ghc-7.10` branch to that commit.

**Comment by imalsogreg** [comment]
Thanks for the detective work. Yes, haskell/primitive@4592a2d had a breaking change without a version bump. Linking to haskell/primitive@29cb0db brings us back to the release commit for primitive 0.5.4.

Running `ghcjs-boot --dev --ghcjs-boot-dev-branch ghc-7.10` I am getting thing error: 
```
applying patch: patches/primitive.patch
/home/greghale/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs/ghcjs-boot/boot/primitive$ [git]: /usr/bin/git "apply" "../../patches/primitive.patch"
/usr/bin/git apply ../../patches/primitive.patch
error: patch failed: primitive.cabal:37
error: primitive.cabal: patch does not apply
ghcjs-boot: error running: /usr/bin/git apply ../../patches/primitive.patch
exit status: 1
stderr: error: patch failed: primitive.cabal:37
error: primitive.cabal: patch does not apply
```

Yes, the patch file at https://github.com/ghcjs/ghcjs-boot/blob/ghc-7.10/patches/primitive.patch  doesn't match the file it's trying to patch.

**Comment by luite** [comment]
Ah that patch shouldn't really be there I think, for ghc 7.10 it should probably include primitive 0.6 instead, rather than bumping bounds on older released packages (0.6 didn't exist yet when i started the ghc 7.10 branch)

**Comment by luite** [comment]
Hm, actually that patch should be ok, since hvr did the same change in a metadata edit on hackage

**Comment by imalsogreg** [comment]
Ok. I assumed ghcjs was somehow tied to primitive-0.5.4, but if you can support primitive 0.6 instead, seems all the better!

**Comment by luite** [comment]
I've updated the 0.5.4.0 patch, which should make it work again. It should be bumped to 0.6 at some point, but I'll have to do a bit more testing for that.

**Comment by imalsogreg** [comment]
Everything working. A thousand thanks!
