### ISSUE TITLE
Permission denied, maybe due to wrong file access mode

### ISSUE THREAD

**Issue by danse** [ghcjs/ghcjs-boot#29]
While running the boot i get the following error:

```
/nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/lib/ghc-7.10.1/include$ cp_r ./ -> /home/francesco/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs/include_native
ghcjs-boot: 
during copy from: /nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/lib/ghc-7.10.1/include/./HsFFI.h to: /home/francesco/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs/include_native/./HsFFI.h
Exception: /home/francesco/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs/include_native/./HsFFI.h: openBinaryFile: permission denied (Permission denied)
```

I can correctly read the file, from another shell:

```
 ~ $ head -n2 /nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/lib/ghc-7.10.1/include/./HsFFI.h
/* -----------------------------------------------------------------------------
 *
 ~ $ 
```

It seems that the command is trying to open the header file as a binary file. I am running the command as in the doc:

```
ghcjs-boot --dev --ghcjs-boot-dev-branch ghc-7.10
```

My clone of `ghcjs` is at c1b6239b0289371dc6b8d17dfd845c14bd4dc490, and my clone of `ghcjs-prim` at bd83ce26f7e32fa9dc6c762d05ca595589d7b1a3

**Comment by luite** [comment]
hmm, I've seen this error before, but I don't know what causes it... Did it work ok the first time, but failed after that? I suspect it's trying to overwrite the file, but the file has been created without write permissions.

**Comment by danse** [comment]
The file cannot be written, indeed, being part of a Nix package. It failed at the first attempt.

**Comment by luite** [comment]
Oh i meant the target file, the one in `~/.ghcjs`, can you check if that one is writable?

**Comment by danse** [comment]
You are right! The target file is not writable!

**Comment by luite** [comment]
what are the permissions of the source? i wonder if it's copying these permissions and getting itself into trouble

**Comment by danse** [comment]
Yes, that seems to be the case:
```
 ~ $ lt /home/francesco/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs/include_native/./HsFFI.h
-r--r--r-- 1 francesco francesco 6030 Jul 18 18:59 /home/francesco/.ghcjs/x86_64-linux-0.1.0-7.10.1/ghcjs/include_native/./HsFFI.h
 ~ $ lt /nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/lib/ghc-7.10.1/include/./HsFFI.h
-r--r--r-- 1 francesco francesco 6030 Jan  1  1970 /nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/lib/ghc-7.10.1/include/./HsFFI.h
```

**Comment by danse** [comment]
For now, as a workaround, some iterations of:

     ~ $ chmod -R +w /home/francesco/.ghcjs/ && ghcjs-boot --dev --ghcjs-boot-dev-branch ghc-7.10

Enabled me to finally overcome these errors :smiley:

**Comment by luite** [comment]
I'll update the `ghcjs-boot` program to better deal with this

**Comment by hamishmack** [comment]
It seems like this is a nix related issue and nix has very good support for ghcjs now.  I presume this issue was fixed or is no longer relevant.
